/**
 * Supabase database types — placeholder until first migration runs.
 * Generated by `supabase gen types typescript --local > lib/db/types.ts` after migrations.
 * For now, this is a minimal stub so type checking passes during early scaffolding.
 */

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
