DROP FUNCTION IF EXISTS process_deposit(UUID, BIGINT, TEXT);
DROP FUNCTION IF EXISTS choose_cycle_end_action(UUID, TEXT, BIGINT);
DROP FUNCTION IF EXISTS generate_kid_login_code(UUID, UUID, TEXT, TIMESTAMPTZ);
